### ISSUE TITLE
PostgresqlConnectionFactory$PostgresqlConnectionException Isnt a public class.

### ISSUE THREAD

**Issue by craftxbox** [r2dbc/r2dbc-postgresql#226] opened 2020-01-12 04:58 UTC
PostgresConnectionException is marked simply as static, without setting a privacy modifier, thus making it not possible to catch() a connectionexception (or instanceof it)

**Comment by mp911de** [comment] 2020-01-12 09:23
`PostgresConnectionException` is by design package-private. Use `R2dbcNonTransientResourceException` instead. This way you interact with [SPI exceptions](https://r2dbc.io/spec/0.8.0.RELEASE/spec/html/#exceptions.categorized) rather than with implementation-specific exceptions as the implementation may of a driver may change at any time.

Can you give us some background why you want to catch `PostgresConnectionException` directly?

**Comment by craftxbox** [comment] 2020-01-12 21:04
I'd like to specifically catch it because we're trying to have a case to check if a query failed because the server was not online/unreachable, as opposed to a permanent failure not caused by the database being unreachable

**Comment by mp911de** [comment] 2020-01-13 07:01
You can identify that case by inspecting the cause which is an instance of `ConnectException`. Closing as we don't have plans to change the design.

**Closed by mp911de** 2020-01-13 07:01 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
