### ISSUE TITLE
Spring data with postgress and r2dbc does not work 

### ISSUE THREAD

**Issue by abhinav-jain09** [r2dbc/r2dbc-postgresql#194] opened 2019-11-18 15:30 UTC
Hello All,

I am trying to run simple spring boot application with spring data and r2dbc but when i run select query it does return any record.

configuration 
```
package com.ns.configuration;

import io.r2dbc.postgresql.PostgresqlConnectionConfiguration;
import io.r2dbc.postgresql.PostgresqlConnectionFactory;
import io.r2dbc.spi.ConnectionFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.r2dbc.config.AbstractR2dbcConfiguration;
import org.springframework.data.r2dbc.dialect.PostgresDialect;
import org.springframework.data.r2dbc.function.DatabaseClient;
import org.springframework.data.r2dbc.function.DefaultReactiveDataAccessStrategy;
import org.springframework.data.r2dbc.repository.config.EnableR2dbcRepositories;
import org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactory;
import org.springframework.data.relational.core.mapping.RelationalMappingContext;

@Configuration
@EnableR2dbcRepositories("com.ns.repository")
public class R2DBCConfiguration extends AbstractR2dbcConfiguration {
    @Bean
    @Override
    public PostgresqlConnectionFactory connectionFactory() {
        return new PostgresqlConnectionFactory(PostgresqlConnectionConfiguration
                .builder()
                .host("localhost")
                .database("employee")
                .username("postgres")
                .password("nssdw")
                .port(5432)
                .build());
    }

@Bean
public DatabaseClient databaseClient(ConnectionFactory connectionFactory){
   return DatabaseClient.builder().connectionFactory(connectionFactory).build();
}

@Bean
    R2dbcRepositoryFactory repositoryFactory(DatabaseClient client){
    RelationalMappingContext context = new RelationalMappingContext();
    context.afterPropertiesSet();
    return new R2dbcRepositoryFactory(client,context, new DefaultReactiveDataAccessStrategy(new PostgresDialect()));


}

}

```

Controller 
```
package com.ns.controller;

import com.ns.entities.Name;
import com.ns.repository.NameRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Mono;

@RestController
public class EventDrivenController {


@Autowired
private NameRepository repositoryEvent;



@GetMapping(value = "/pools" )
    public Mono<Name> getEmployee() {

    Mono<Name> mono = repositoryEvent.findById(1);
    repositoryEvent.findById(1).doOnEach(System.out::println);
    return mono;


}
}```

Repository 
```
package com.ns.repository;

import com.ns.entities.Name;
import org.springframework.data.r2dbc.repository.query.Query;
import org.springframework.data.repository.reactive.ReactiveCrudRepository;
import org.springframework.stereotype.Repository;
import reactor.core.publisher.Mono;

@Repository
public interface NameRepository extends ReactiveCrudRepository<Name,Integer> {

@Query( "SELECT name_id, last_name, first_name FROM name WHERE name_id = $1")
      Mono<Name> findById(Integer id);

}
```
Entity
```

package com.ns.entities;

import org.springframework.data.annotation.Id;

import java.io.Serializable;

public class Name implements Serializable {
    @Id
    private Integer nameId;
    private String lastName;
    private String firstName;

    public Integer getNameId() {
        return nameId;
    }

    public void setNameId(Integer nameId) {
        this.nameId = nameId;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Override
    public String toString() {
        return "Name{" +
                "nameId=" + nameId +
                ", lastName='" + lastName + '\'' +
                ", firstName='" + firstName + '\'' +
                '}';
    }
}
```

```
webclient 

```
package com.ns.client;

import com.ns.entities.Name;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

public class NameWebClient {


    public void  callwebclient() {
        WebClient client = WebClient.create("http://localhost:8080");
        Mono<Name> employeeMono = client.get()
                .uri("/pools")
                .retrieve()
                .bodyToMono(Name.class);
  
        employeeMono.subscribe(System.out::println);
    }

}
```

when I try to print I do not get any value from the database

```
2019-11-18 16:29:20.963  INFO 26857 --- [           main] com.ns.EventDrivenSystemApplication      : Starting EventDrivenSystemApplication on static.kpn.net with PID 26857 (/Users/abhinav/development/workspace/eventdrivenpoc/target/classes started by abhinav in /Users/abhinav/development/workspace/eventdrivenpoc)
2019-11-18 16:29:20.965  INFO 26857 --- [           main] com.ns.EventDrivenSystemApplication      : No active profile set, falling back to default profiles: default
2019-11-18 16:29:21.303  INFO 26857 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-11-18 16:29:21.465  INFO 26857 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 156ms. Found 1 repository interfaces.
2019-11-18 16:29:22.454  INFO 26857 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
2019-11-18 16:29:22.458  INFO 26857 --- [           main] com.ns.EventDrivenSystemApplication      : Started EventDrivenSystemApplication in 1.893 seconds (JVM running for 2.222)
2019-11-18 16:29:22.711 DEBUG 26857 --- [actor-tcp-nio-1] o.s.d.r.function.DefaultDatabaseClient   : Executing SQL statement [SELECT name_id, last_name, first_name FROM name WHERE name_id = $1]

```

**Comment by mp911de** [comment] 2019-11-18 16:06
Have you tried reproducing your issue using R2DBC Postgres API?

**Comment by abhinav-jain09** [comment] 2019-11-18 16:31
you mean without using spring data just simple application with r2dbc api ? Well I really wanna use spring data for it. Do you want me to try with r2dbc api?

**Comment by mp911de** [comment] 2019-11-18 16:50
Exactly. If you can reproduce the issue with the driver API, then your issue belongs here. If not, then your issue is likely related to Spring Data.

**Comment by abhinav-jain09** [comment] 2019-11-18 17:02
It’s very strange that I did not find any working example by spring data anywhere.

**Comment by abhinav-jain09** [comment] 2019-11-19 13:08
I checked the simple insert which is in the readme file of this project, it also not working. I do not get any records inserted.  @mp911de

**Comment by mp911de** [comment] 2019-11-19 13:12
Would you mind sharing the code that you've used to insert rows that is not working for you in the context of a running project, ideally a GitHub repository?

**Comment by abhinav-jain09** [comment] 2019-11-19 13:15
```
        Mono<Connection> connectionMono = Mono.from(connectionFactory().create());

        connectionMono.flatMapMany(connection -> connection
                .createStatement("INSERT INTO name (name_id, first_name, last_name) VALUES ($1, $2, $3)")
                .bind("$1", 1)
                .bind("$2", "Walter")
                .bind("$3", "White")
                .execute());
	}

    public static ConnectionFactory  connectionFactory() {
        return new PostgresqlConnectionFactory(PostgresqlConnectionConfiguration
                .builder()
                .host("localhost")
                .database("employee")
                .username("postgres")
                .password("nssdw")
                .port(5432)
                .build());
    }
```
If you want I can cheking this code to github but its pretty simple just connection and insert

**Comment by mp911de** [comment] 2019-11-19 13:50
The resulting `Publisher` (of `flatMapMany(… .execute())`) isn't subscribed to. In Reactive Programming, nothing happens until you subscribe.

In an application, you typically hand back the `Publisher` to an endpoint handler, that handles subscription for you.

In a test, you would initiate a subscription by either using Project Reactor's `StepVerifier` or by calling `.block()`.

**Comment by abhinav-jain09** [comment] 2019-11-19 14:11
```
  connectionMono.flatMapMany(connection -> connection
                .createStatement("INSERT INTO employee_name (name_id, first_name, last_name) VALUES ($1, $2, $3)")
                .bind("$1", 1)
                .bind("$2", "Walter")
                .bind("$3", "White")
                .execute()).subscribe(System.out::println);
	}
``` 
Now I subscribe to it still it does not work

**Comment by mp911de** [comment] 2019-11-19 15:05
How exactly `it still it does not work` does materialize? Do you see an exception?

We're not really progressing here.

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) in the form of a GitHub repository that reproduces the problem.

**Comment by abhinav-jain09** [comment] 2019-11-19 15:20
okay, I am going to make repo for it . when I say it does not work meaning it does not insert the record in the database and I do not see any exception on the console. I expect that record should be inserted with the following code 
```
 connectionMono.flatMapMany(connection -> connection
                .createStatement("INSERT INTO employee_name (name_id, first_name, last_name) VALUES ($1, $2, $3)")
                .bind("$1", 1)
                .bind("$2", "Walter")
                .bind("$3", "White")
                .execute()).subscribe(System.out::println);
	}```

**Comment by fjacobs** [comment] 2019-11-21 22:17
FYI: Subscribe seem to behave different for H2 and Postgres. When using H2 the following will write a table to the DB, but not when using Postgres:

```     Mono<Connection> connectionMono = Mono.from(connectionFactory.create());
        connectionMono.flatMapMany(connection -> connection
                .createStatement(  "CREATE TABLE customer ( id SERIAL PRIMARY KEY, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL);")
                .execute())
                .subscribe();
```

**Comment by mp911de** [comment] 2019-11-22 08:39
Please make sure to consume the `Result` object. Just executing the statement without consuming the `Result` can result in undesired effects. R2DBC consumes the data as stream from the wire protocol so not consuming `Result` (either `getRowsUpdated()` or `map(…)`) can leave statements unexecuted.

So rewriting your code to 

```
        connectionMono.flatMapMany(connection -> connection
                .createStatement(  "CREATE TABLE customer ( id SERIAL PRIMARY KEY, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL);")
                .execute()).flatMap(Result::getRowsUpdated)
                .subscribe();
```

should help you to get things going.

**Comment by mp911de** [comment] 2019-12-02 07:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-12-02 07:42 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
