### ISSUE TITLE
Sql exceptions handling

### ISSUE THREAD

**Issue by vadim-shb** [r2dbc/r2dbc-postgresql#118] opened 2019-06-02 22:28 UTC
I don't understand r2dbc exception handling policies
I have a snippet (r2dbc-postgresql[1.0.0.M7] + spring-data-r2dbc[1.0.0.M2]):

```
@Test
void test() {
    var connectionConfiguration = PostgresqlConnectionConfiguration.builder()
            .host("localhost")
            .database("db")
            .port(5432)
            .username("test")
            .password("test")
            .build();

    var connectionFactory = new PostgresqlConnectionFactory(connectionConfiguration);
    var databaseClient = DatabaseClient.create(connectionFactory);

    databaseClient.execute()
            .sql("CREATE TABLE foo (id VARCHAR(36) NOT NULL PRIMARY KEY)")
            .then().block();

    databaseClient.execute().sql("insert into foo(id) values ('2')").then().block();
    databaseClient.execute().sql("insert into foo(id) values ('2')").then().block();
}
```

I expect to get some kind of SQL-exception because of unique constraint violation, but instead, I just have
```
 ERROR | i.r.p.client.ReactorNettyClient | Error: SEVERITY_LOCALIZED=ERROR, SEVERITY_NON_LOCALIZED=ERROR, CODE=23505, MESSAGE=duplicate key value violates unique constraint "foo_pkey", DETAIL=Key (id)=(2) already exists., SCHEMA_NAME=public, TABLE_NAME=foo, CONSTRAINT_NAME=foo_pkey, FILE=nbtinsert.c, LINE=535, ROUTINE=_bt_check_unique
```
in logs and a hanging test...
Do I miss something or this is a bug?

**Comment by Squiry** [comment] 2019-06-04 08:45
You'll get your error if you try to subscribe on getRowsUpdated/map of Result. I don't know if it's 
expected behavior or not, the fix is pretty simple so we need a word from someone of r2dbc team.

**Comment by schauder** [comment] 2019-06-04 14:21
I tried to reproduce this but failed. I get the log message you mentioned plus an exception immediately after that. 

Could you create a testcase reproducing the issue? 

Also, at this point we should probably consider it a Spring Data R2DBC bug since that is the API you are using and there is no indication that this is specific to r2dbc-postgresql. 

`AbstractDatabaseClientIntegrationTests` is probably a good place to add a test.
But a standalone project on github would be just fine as well.

**Comment by Squiry** [comment] 2019-06-04 17:20
@schauder 
try this on master (insert it in `PostgresqlExample` class)
```java
    @Test
    void issue118() {
        getJdbcOperations().execute("CREATE TABLE foo (id VARCHAR(36) NOT NULL PRIMARY KEY)");
        getJdbcOperations().execute("insert into foo(id) values ('2')");

        PostgresqlConnection connection = ((PostgresqlConnectionFactory) getConnectionFactory()).create().block();
        try {
            connection.createStatement("insert into foo(id) values ('2')")
                .execute()
                .as(StepVerifier::create)
                .expectErrorSatisfies(e -> assertThat(e).isInstanceOf(PostgresqlServerErrorException.class)
                    .hasFieldOrPropertyWithValue("code", "23505")
                    .hasFieldOrPropertyWithValue("detail", Optional.of("Key (id)=(2) already exists.")))
                .verify();
        } finally {
            connection.close().block();
        }
    }
```

It could be fixed with adding `.handle(PostgresqlExceptionFactory::handleErrorResponse)` after `SimpleQueryMessageFlow.execute` and `ExtendedQueryMessageFlow.execute`.

**Comment by schauder** [comment] 2019-06-05 05:38
@Squiry I'm a little dense it seems.

The test passes.
This demonstrates the behavior @vadim-shb expects but doesn't see: The `Flux` emits an error signal and completes.

What the OP reported is: No error emitted (only logged) and `block()` blocking for ever which indicates the `Publisher` didn't complete.

**Comment by Squiry** [comment] 2019-06-05 07:03
@schauder 
```
10:00:16.073 reactor-tcp-nio-1  io.r2dbc.postgresql.client.ReactorNettyClient           Error: SEVERITY_LOCALIZED=ERROR, SEVERITY_NON_LOCALIZED=ERROR, CODE=23505, MESSAGE=duplicate key value violates unique constraint "foo_pkey", DETAIL=Key (id)=(2) already exists., SCHEMA_NAME=public, TABLE_NAME=foo, CONSTRAINT_NAME=foo_pkey, FILE=nbtinsert.c, LINE=535, ROUTINE=_bt_check_unique

java.lang.AssertionError: expectation "expectErrorSatisfies" failed (expected: onError(); actual: onNext(PostgresqlResult{codecs=io.r2dbc.postgresql.codec.DefaultCodecs@77279ebc, rowMetadata=MonoMap, rows=FluxMap, rowsUpdated=MonoHandleFuseable}))
```
It failes for me too.

**Comment by vadim-shb** [comment] 2019-06-05 07:53
I've made a pure r2dbc test and it doesn't block thread like spring-data-r2bc is.
```
@Test
    public void test() {
        var connectionConfiguration = PostgresqlConnectionConfiguration.builder()
                .host("localhost")
                .database("foo")
                .port(5432)
                .username("test")
                .password("test")
                .build();

        var connectionFactory = new PostgresqlConnectionFactory(connectionConfiguration);

        PostgresqlConnection connection = connectionFactory.create().block();
        try {
            connection.createStatement("CREATE TABLE foo (id VARCHAR(36) NOT NULL PRIMARY KEY)").execute().subscribe();
            connection.createStatement("insert into foo(id) values ('2')").execute().blockFirst();
            connection.createStatement("insert into foo(id) values ('2')").execute().blockFirst();
            // waiting for exception here but nothing comes
            connection.createStatement("insert into foo(id) values ('2')").execute().subscribe(res -> {
                res.getRowsUpdated().doOnError(ex -> {
                    // waiting for exception here but nothing comes
                    log.error("r2dbc exception", ex);
                });
            }, ex -> {
                // waiting for exception here but nothing comes
                log.error("r2dbc exception", ex);
            });
        } finally {
            connection.close().block();
        }
    }
```
I still can't get an exception in the main thread, but it's probably because of my poor understanding of the API.

**Comment by Squiry** [comment] 2019-06-05 08:43
```java
     res.getRowsUpdated().doOnError(ex -> {
                    // waiting for exception here but nothing comes
                    log.error("r2dbc exception", ex);
                });
```
You didn't subscribe on this mono. you should do something like this

```java
        Flux.from(connection.createStatement("insert into foo(id) values ('2')").execute())
            .flatMap(res -> res.getRowsUpdated())
            .doOnError(ex -> {
                // waiting for exception here but nothing comes
                log.error("r2dbc exception", ex);
            })
            .blockLast();
```
You will not get an exceptio on second `connection.createStatement("insert into foo(id) values ('2')").execute().blockFirst();` anyway, I don't know how @schauder got it.

**Comment by schauder** [comment] 2019-06-05 09:17
It was a mistake on my side. I can reproduce the failing test @Squiry showed above.

@Squiry since you seemed to have a fix in mind, do you care to provide a PR?

**Comment by Squiry** [comment] 2019-06-05 15:15
@schauder sure, #119

**Closed** 2019-07-23 20:10 UTC
